' Kiosk Client Installer - Custom Actions
' VBScript custom actions for configuration validation and file generation

Option Explicit

' Validate Configuration (Silent Install)
' Ensures required properties are provided for silent installation
Function ValidateConfig()
    Dim serverUrl, deviceToken, errorMsg

    ' Get properties from MSI
    serverUrl = Session.Property("SERVER_URL")
    deviceToken = Session.Property("DEVICE_TOKEN")

    ' Log for debugging
    Session.Log("ValidateConfig: SERVER_URL = " & serverUrl)
    Session.Log("ValidateConfig: DEVICE_TOKEN = " & (Len(deviceToken) > 0 And "***SET***" Or "***EMPTY***"))

    ' Check if this is a silent install (UILevel = 2)
    Dim uiLevel
    uiLevel = Session.Property("UILevel")
    Session.Log("ValidateConfig: UILevel = " & uiLevel)

    If CInt(uiLevel) = 2 Then
        ' Silent install - validate required properties
        errorMsg = ""

        ' Validate SERVER_URL
        If Len(serverUrl) = 0 Then
            errorMsg = errorMsg & "Required property SERVER_URL is missing. "
        ElseIf Not (Left(serverUrl, 7) = "http://" Or Left(serverUrl, 8) = "https://") Then
            errorMsg = errorMsg & "SERVER_URL must start with http:// or https://. "
        End If

        ' Validate DEVICE_TOKEN
        If Len(deviceToken) = 0 Then
            errorMsg = errorMsg & "Required property DEVICE_TOKEN is missing. "
        End If

        ' If validation failed, log error and abort
        If Len(errorMsg) > 0 Then
            Session.Log("ValidateConfig ERROR: " & errorMsg)
            Session.Message &H02000000 Or &H00000004, errorMsg & vbCrLf & vbCrLf & "For silent installation, you must provide:" & vbCrLf & "  msiexec /i KioskClient.msi /qn SERVER_URL=http://... DEVICE_TOKEN=..."
            ValidateConfig = 1603 ' Error - abort installation
            Exit Function
        End If
    End If

    Session.Log("ValidateConfig: SUCCESS")
    ValidateConfig = 0 ' Success
End Function

' Create .env Configuration File
' Generates .env file from MSI properties
Function CreateEnvFile()
    On Error Resume Next

    Dim fso, envFile, installDir, envPath
    Dim serverUrl, deviceToken, displayWidth, displayHeight, kioskMode, logLevel

    ' Get installation directory
    installDir = Session.Property("CustomActionData")
    If Len(installDir) = 0 Then
        installDir = Session.Property("INSTALLDIR")
    End If

    ' Ensure trailing backslash
    If Right(installDir, 1) <> "\" Then
        installDir = installDir & "\"
    End If

    envPath = installDir & "app\.env"

    Session.Log("CreateEnvFile: Writing to " & envPath)

    ' Get configuration properties
    serverUrl = Session.Property("SERVER_URL")
    deviceToken = Session.Property("DEVICE_TOKEN")
    displayWidth = Session.Property("DISPLAY_WIDTH")
    displayHeight = Session.Property("DISPLAY_HEIGHT")
    kioskMode = Session.Property("KIOSK_MODE")
    logLevel = Session.Property("LOG_LEVEL")

    ' Set defaults if not provided
    If Len(serverUrl) = 0 Then serverUrl = "http://localhost:5001"
    If Len(displayWidth) = 0 Then displayWidth = "1920"
    If Len(displayHeight) = 0 Then displayHeight = "1080"
    If Len(kioskMode) = 0 Then kioskMode = "true"
    If Len(logLevel) = 0 Then logLevel = "info"

    Session.Log("CreateEnvFile: SERVER_URL = " & serverUrl)
    Session.Log("CreateEnvFile: DEVICE_TOKEN = " & (Len(deviceToken) > 0 And "***SET***" Or "***EMPTY***"))
    Session.Log("CreateEnvFile: DISPLAY_WIDTH = " & displayWidth)
    Session.Log("CreateEnvFile: DISPLAY_HEIGHT = " & displayHeight)
    Session.Log("CreateEnvFile: KIOSK_MODE = " & kioskMode)
    Session.Log("CreateEnvFile: LOG_LEVEL = " & logLevel)

    ' Create FileSystemObject
    Set fso = CreateObject("Scripting.FileSystemObject")

    ' Check if .env already exists (upgrade scenario)
    If fso.FileExists(envPath) Then
        ' Backup existing .env
        Dim backupPath
        backupPath = envPath & ".backup"
        If fso.FileExists(backupPath) Then
            fso.DeleteFile backupPath, True
        End If
        fso.CopyFile envPath, backupPath, True
        Session.Log("CreateEnvFile: Backed up existing .env to " & backupPath)

        ' If no new token provided, keep existing (upgrade without reconfiguration)
        If Len(deviceToken) = 0 Then
            Session.Log("CreateEnvFile: No new DEVICE_TOKEN provided, keeping existing .env")
            CreateEnvFile = 0 ' Success - keep existing
            Exit Function
        End If
    End If

    ' Create new .env file
    Set envFile = fso.CreateTextFile(envPath, True)

    ' Write configuration
    envFile.WriteLine("# Kiosk Client Configuration")
    envFile.WriteLine("# Generated by installer on " & Now())
    envFile.WriteLine("")
    envFile.WriteLine("# Backend Server URL")
    envFile.WriteLine("SERVER_URL=" & serverUrl)
    envFile.WriteLine("")
    envFile.WriteLine("# Device Authentication Token")
    envFile.WriteLine("DEVICE_TOKEN=" & deviceToken)
    envFile.WriteLine("")
    envFile.WriteLine("# Display Settings")
    envFile.WriteLine("DISPLAY_WIDTH=" & displayWidth)
    envFile.WriteLine("DISPLAY_HEIGHT=" & displayHeight)
    envFile.WriteLine("KIOSK_MODE=" & kioskMode)
    envFile.WriteLine("")
    envFile.WriteLine("# Logging")
    envFile.WriteLine("LOG_LEVEL=" & logLevel)
    envFile.WriteLine("")
    envFile.WriteLine("# Optional: Custom Chromium Path")
    envFile.WriteLine("# PUPPETEER_EXECUTABLE_PATH=")
    envFile.WriteLine("")
    envFile.WriteLine("# Health Check Interval (milliseconds)")
    envFile.WriteLine("HEALTH_CHECK_INTERVAL=60000")
    envFile.WriteLine("")
    envFile.WriteLine("# Screenshot Interval (milliseconds)")
    envFile.WriteLine("SCREENSHOT_INTERVAL=300000")

    envFile.Close()

    If Err.Number <> 0 Then
        Session.Log("CreateEnvFile ERROR: " & Err.Description)
        CreateEnvFile = 1603 ' Error
        Exit Function
    End If

    Session.Log("CreateEnvFile: SUCCESS - .env file created")
    CreateEnvFile = 0 ' Success
End Function
